---
defaults:
  # graphite defaults are now in the cephmetrics-common role since the
  # ceph-collectd role needs access to them
  replace_dashboards: true
  update_alerts: false
  grafana:
    container_name: "grafana/grafana"
    container_cpu_period: 100000
    container_cpu_cores: 2
    # container_memory is in GB
    container_memory: 4
    # version currently only applies to containers
    version: 5.1.3
    uid: 472
    datasource: Local
    # You need to change these in the web UI on an already deployed machine, first
    # New deployments work fine
    admin_user: admin
    admin_password: admin
    plugins:
      - vonage-status-panel
      - grafana-piechart-panel
devel_packages:
  yum:
    # unzip is needed to extract the Vonage plugin
    - unzip
    - grafana
    # for dashUpdater.py
    - PyYAML
    - python-requests
  apt:
    # unzip is needed to extract the Vonage plugin
    - unzip
    - grafana
    # for dashUpdater.py
    - python-yaml
    - python-requests
