---
defaults:
  # graphite defaults are now in the ceph-defaults role since the
  # ceph-collectd role needs access to them
  dashboards_path: "dashboards"
  replace_dashboards: true
  update_alerts: false
  grafana:
    container_name: "grafana/grafana"
    container_tag: latest
    container_cpu_period: 100000
    container_cpu_cores: 2
    # container_memory is in GB
    container_memory: 4
    uid: 472
    datasource: Local
    plugins:
      - vonage-status-panel
      - grafana-piechart-panel
devel_packages:
  yum:
    # unzip is needed to extract the Vonage plugin
    - unzip
    - grafana
    # for dashUpdater.py
    - PyYAML
    - python-requests
  apt:
    # unzip is needed to extract the Vonage plugin
    - unzip
    - grafana
    # for dashUpdater.py
    - python-yaml
    - python-requests
