---
- name: Check firewalld status
  shell: "systemctl show firewalld | grep UnitFileState"
  register: firewalld_status
  failed_when: false
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Open port for the mgr prometheus module
  firewalld:
    port: "{{ item }}"
    zone: "{{ firewalld_zone }}"
    state: enabled
    immediate: true
    permanent: true
  with_items:
    - 9283/tcp
  when: "'enabled' in firewalld_status.stdout"
